import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Playwright runs (both gitignored); the trace viewer is
    // minified third-party code that isn't ours to lint.
    "playwright-report/**",
    "test-results/**",
    // Promo render output (gitignored).
    "promo/out/**",
  ]),
  // GitHub Pages landing page (site/): plain browser scripts.
  {
    files: ["site/**/*.js"],
    languageOptions: { globals: { window: "readonly", document: "readonly", navigator: "readonly", Image: "readonly", setTimeout: "readonly" } },
  },
  // Promo frame renderer and spot loader: CommonJS, run by Node inside the promo image.
  {
    files: ["promo/render.js", "promo/spot-config.js"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
]);

export default eslintConfig;
