/**
 * README screenshots, regenerated by .github/workflows/visual-docs.yml.
 *
 *   npx playwright test -c playwright.visual-docs.config.ts
 *
 * DB-free: every /api call is mocked (e2e/fixtures/demo-portfolio.ts) with fixed
 * demo data and a frozen clock, so output only changes when the UI does and the
 * bot PR doesn't churn on "3 days ago" labels. Writes docs/screenshots/*.png.
 */
import { test, expect, type Page } from '@playwright/test';
import { NOW, prepare, signedInContext } from '../fixtures/demo-portfolio';

const OUT = 'docs/screenshots';

test.use({ viewport: { width: 1280, height: 800 }, colorScheme: 'dark' });

test.beforeEach(async ({ page }) => {
  await prepare(page);
});

/**
 * Rows fetch their doc status after the table renders. Capturing while some
 * still show the loading dots made the same UI produce different PNGs run to
 * run (and a bot PR on every push), so every shot waits for them to clear.
 */
async function shoot(page: Page, name: string) {
  await expect(page.locator('[aria-label="Loading doc status"], [aria-label="Loading docs"]')).toHaveCount(0, { timeout: 30_000 });
  await page.screenshot({ path: `${OUT}/${name}.png` });
}

test('dashboard', async ({ page }) => {
  await page.goto('/');
  // Scoped to the desktop table: the hidden mobile cards render the same names.
  await expect(page.locator('table tbody')).toContainText('agent-board', { timeout: 30_000 });
  await shoot(page, 'dashboard');
});

test('repo details', async ({ page }) => {
  await page.goto('/');
  // Sorted by name, so the vigil row is last; expand it via its description cell.
  const row = page.locator('table tbody tr', { hasText: 'Portfolio health dashboard' });
  await expect(row).toBeVisible({ timeout: 30_000 });
  await row.locator('td').nth(1).click();
  await expect(page.getByRole('heading', { name: 'Repository Stats' })).toBeVisible({ timeout: 15_000 });
  await page.getByRole('heading', { name: 'Repository Stats' }).scrollIntoViewIfNeeded();
  await shoot(page, 'repo-details');
});

test('pmo', async ({ page }) => {
  await signedInContext(page);
  await page.goto('/pmo');
  await expect(page.getByText('Portfolio Pipeline')).toBeVisible();
  await expect(page.getByRole('article', { name: 'nitsuah/skyview' })).toBeVisible();
  await shoot(page, 'pmo');
});

// Screenshots named after a feature id in promo/spots.json are linked to that
// feature automatically (`npm run showcase -- apply .`).
test('per-repo chat', async ({ page }) => {
  await signedInContext(page);
  // A seeded thread, so the shot never calls an AI provider. The reply carries a
  // doc-edit proposal card (chat-driven-doc-edit-proposals).
  const at = NOW.toISOString();
  const thread = {
    vigil: [
      { id: 'u1', role: 'user', content: 'Summarize my stale docs', createdAt: at },
      {
        id: 'a1', role: 'assistant', createdAt: at,
        content: 'Two docs need attention:\n\n- **ROADMAP.md** still lists *AI-assisted roadmap management* as planned for 2027 Q1 with no linked PR.\n- **METRICS.md** was last updated 41 days ago, so the 81.2% coverage figure may be stale.\n\nI drafted a METRICS.md refresh below.',
        proposal: { docType: 'metrics', summary: 'Refresh METRICS.md with the current coverage and test counts', content: '# Metrics\n\n| Metric | Value |\n|---|---|\n| Coverage | 81.2% |\n| Test files | 64 |\n' },
      },
    ],
  };
  await page.addInitScript((t) => {
    window.localStorage.setItem('vigil.repo-chat.v1.demo%40example.com', t);
  }, JSON.stringify(thread));
  await page.goto('/');
  await expect(page.locator('table tbody')).toContainText('agent-board', { timeout: 30_000 });
  await page.locator('table tbody').getByRole('button', { name: 'Chat about vigil' }).click();
  await expect(page.getByRole('dialog')).toContainText('Refresh METRICS.md');
  await shoot(page, 'per-repo-conversational-interface');
});

test('mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByText('Drone services marketplace').first()).toBeVisible({ timeout: 30_000 });
  await shoot(page, 'responsive-design');
});
