/**
 * README screenshots, regenerated by .github/workflows/visual-docs.yml.
 *
 *   npx playwright test -c playwright.visual-docs.config.ts
 *
 * DB-free: every /api call is mocked (same approach as e2e/mocked) with fixed
 * demo data and a frozen clock, so output only changes when the UI does and the
 * bot PR doesn't churn on "3 days ago" labels. Writes docs/screenshots/*.png.
 */
import { test, expect } from '@playwright/test';
import type { BrowserContext, Page } from '@playwright/test';
import { encode } from 'next-auth/jwt';

const OUT = 'docs/screenshots';
const NOW = new Date('2026-09-25T12:00:00Z');

const repo = <T extends { name: string; health_score: number }>(over: T) => ({
  id: over.name, full_name: `nitsuah/${over.name}`, url: `https://github.com/nitsuah/${over.name}`,
  homepage: null, topics: [], is_fork: false, is_hidden: false, is_archived: false,
  stars: 4, forks: 1, open_issues: 1, open_prs: 1, branches_count: 3, contributor_count: 1, bus_factor: 1,
  commit_frequency: '9.5', avg_pr_merge_time_hours: '14.2', token_density: '7.9', comment_to_code_ratio: '0.16',
  ci_status: 'passing', last_commit_date: '2026-09-24T00:00:00Z', last_synced: '2026-09-25T00:00:00Z',
  updated_at: '2026-09-25T00:00:00Z', created_at: '2025-01-01T00:00:00Z',
  ...over,
});

const REPOS = [
  repo({ name: 'vigil', description: 'Portfolio health dashboard, PMO, and MCP server', language: 'TypeScript', repo_type: 'web-app', health_score: 92, total_loc: 48210, coverage_score: '81.2' }),
  repo({ name: 'agent-board', description: 'Local agent runtime and task board', language: 'Python', repo_type: 'tool', health_score: 78, total_loc: 15320, coverage_score: '64.0' }),
  repo({ name: 'darkmoon', description: 'Multiplayer browser game', language: 'TypeScript', repo_type: 'game', health_score: 71, total_loc: 30110, coverage_score: '52.5', ci_status: 'failing' }),
  repo({ name: 'skyview', description: 'Drone services marketplace', language: 'JavaScript', repo_type: 'web-app', health_score: 64, total_loc: 21900, coverage_score: '40.1' }),
];

const DETAILS = {
  repo: REPOS[0],
  tasks: [
    { id: 't1', title: 'Chat-driven doc editing, stage 3', status: 'todo', section: 'Todo', subsection: 'P2 - Medium' },
    { id: 't2', title: 'Zombie-branch bulk cleanup dialog', status: 'todo', section: 'Todo', subsection: 'P3 - Exploratory' },
  ],
  roadmapItems: [
    { id: 'r1', title: 'AI-assisted roadmap management', quarter: '2027 Q1', status: 'planned' },
    { id: 'r2', title: 'Technical-debt trending', quarter: '2027 Q1', status: 'in-progress' },
  ],
  metrics: [{ name: 'Code Coverage', value: 81.2, unit: '%' }],
  features: [],
  docStatuses: ['readme', 'tasks', 'roadmap', 'features', 'metrics', 'changelog'].map((d) => ({ doc_type: d, exists: true, health_state: 'healthy' })),
  bestPractices: [
    ['branch_protection', 'healthy'], ['ci_cd', 'healthy'], ['gitignore', 'healthy'], ['pre_commit_hooks', 'healthy'],
    ['testing_framework', 'healthy'], ['linting', 'healthy'], ['docker', 'healthy'], ['env_template', 'healthy'],
    ['dependabot', 'healthy'], ['deploy_badge', 'healthy'], ['visual_docs', 'healthy'],
  ].map(([practice_type, status]) => ({ practice_type, status, details: { exists: true, informational: practice_type === 'visual_docs' } })),
  communityStandards: [],
  securityConfig: null,
};

const PMO = {
  repos: REPOS.map((r, i) => ({
    id: r.id, name: r.name, full_name: r.full_name, url: r.url, health_score: r.health_score, ci_status: r.ci_status,
    last_commit_date: r.last_commit_date, open_prs: r.open_prs,
    roadmap: { total: 6 - i, planned: 3, in_progress: 1, in_review: i % 2, done: 2 - (i % 2), stale_count: i === 2 ? 1 : 0 },
    tasks: { total: 9 - i, todo: 6 - i, in_progress: 1, done: 2 },
    in_progress_items: [{ id: `ip-${i}`, repo_id: r.id, title: ['Technical-debt trending', 'GPU model portfolio', '21st.dev UI pass', 'Marketplace backend live'][i], quarter: '2027 Q1', linked_pr_number: i === 2 ? null : 240 + i, agent_task_id: null }],
  })),
  portfolio: { repo_count: 4, roadmap_planned: 12, roadmap_in_progress: 4, roadmap_in_review: 2, roadmap_done: 6, tasks_in_progress: 4, stale_count: 1 },
};

async function mockApi(target: Page | BrowserContext): Promise<void> {
  const json = (body: unknown) => ({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
  await target.route('**/api/repos?*', (route) => route.fulfill(json(REPOS)));
  await target.route('**/api/repo-details/*/trend', (route) => route.fulfill(json({ success: true, snapshots: [] })));
  await target.route('**/api/repo-details/*', (route) => route.fulfill(json(DETAILS)));
  await target.route('**/api/dependencies', (route) => route.fulfill(json({ success: true, nodes: [], edges: [] })));
  await target.route('**/api/gemini-status', (route) => route.fulfill(json({ status: 'ok' })));
  await target.route('**/api/github-rate-limit', (route) => route.fulfill(json({ core: { remaining: 5000, limit: 5000, reset: 0 } })));
  await target.route('**/api/pmo/overview', (route) => route.fulfill(json(PMO)));
}

async function signedInContext(page: Page): Promise<void> {
  const secret = process.env.NEXTAUTH_SECRET;
  if (!secret) throw new Error('NEXTAUTH_SECRET must be set for the visual-docs server and tests');
  const value = await encode({
    token: { name: 'Demo Owner', email: 'demo@example.com', sub: 'demo-owner' },
    secret,
    salt: 'authjs.session-token',
  });
  await page.context().addCookies([{ name: 'authjs.session-token', value, domain: 'localhost', path: '/' }]);
}

test.use({ viewport: { width: 1280, height: 800 }, colorScheme: 'dark' });

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(NOW);
  await mockApi(page);
  // `next dev` renders its dev-tools badge in a <nextjs-portal>; keep it out of the docs.
  await page.addInitScript(() => {
    document.addEventListener('DOMContentLoaded', () => {
      const style = document.createElement('style');
      style.textContent = 'nextjs-portal { display: none !important; }';
      document.head.appendChild(style);
    });
  });
});

test('dashboard', async ({ page }) => {
  await page.goto('/');
  // Scoped to the desktop table: the hidden mobile cards render the same names.
  await expect(page.locator('table tbody')).toContainText('agent-board', { timeout: 30_000 });
  await page.screenshot({ path: `${OUT}/dashboard.png` });
});

test('repo details', async ({ page }) => {
  await page.goto('/');
  // Sorted by name, so the vigil row is last; expand it via its description cell.
  const row = page.locator('table tbody tr', { hasText: 'Portfolio health dashboard' });
  await expect(row).toBeVisible({ timeout: 30_000 });
  await row.locator('td').nth(1).click();
  await expect(page.getByRole('heading', { name: 'Repository Stats' })).toBeVisible({ timeout: 15_000 });
  await page.getByRole('heading', { name: 'Repository Stats' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: `${OUT}/repo-details.png` });
});

test('pmo', async ({ page }) => {
  await signedInContext(page);
  await page.goto('/pmo');
  await expect(page.getByText('Portfolio Pipeline')).toBeVisible();
  await page.screenshot({ path: `${OUT}/pmo.png` });
});
